print("Hello from both GitHub and local computer!")
print("This version combines both edits")
print("Local version: edited locally")
print("GitHub version: edited on GitHub")
print("Greetings from GitHub!")
print("This version was edited on the web")